# Generated by Django 4.1.5 on 2023-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_user',
            name='c_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NV_control.company_name'),
        ),
        migrations.AlterField(
            model_name='office_user',
            name='cell_number_1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='office_user',
            name='cell_number_2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='office_user',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
