# Generated by Django 4.1.5 on 2023-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0002_alter_office_user_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_feese',
            name='max_discount',
            field=models.FloatField(null=True),
        ),
    ]
