# Generated by Django 4.1.5 on 2023-05-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0003_course_feese_max_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Expense_Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=255)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NV_control.company_name')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=1000)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NV_control.company_name')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NV_control.company_expense_catagory')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
