# Generated by Django 4.1.5 on 2023-05-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0006_course_student_waiver_course_student_submited_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Student_Submited',
            new_name='Course_Student_Documents_Submited',
        ),
    ]
