# Generated by Django 4.1.5 on 2023-05-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0007_rename_course_student_submited_course_student_documents_submited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_student_documents_submited',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NV_control.student_user'),
        ),
    ]
