# Generated by Django 4.2.1 on 2023-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0008_alter_course_student_documents_submited_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_expense',
            name='exp_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
