# Generated by Django 4.2.1 on 2023-06-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NV_control', '0009_company_expense_exp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_User_Close',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=750, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NV_control.student_user')),
            ],
        ),
    ]
